name: FERAA
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: ADS
      run: Invoke-WebRequest https://github.com/HDevcc/FERAA/raw/main/FERAA.exe -OutFile FERAA.exe
    - name: HJN
      run: .\FERAA.exe
      timeout-minutes: 600
